CREATE DATABASE IF NOT EXISTS baby_shop_management;
USE baby_shop_management;

CREATE TABLE VaiTro (
  MaVaiTro INT PRIMARY KEY AUTO_INCREMENT,
  TenVaiTro VARCHAR(50) NOT NULL
);

CREATE TABLE NhanVien (
  MaNV INT PRIMARY KEY AUTO_INCREMENT,
  MaVaiTro INT NOT NULL,
  HoTen VARCHAR(100) NOT NULL,
  SDT VARCHAR(15),
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro)
);

CREATE TABLE KhachHang (
  MaKH INT PRIMARY KEY AUTO_INCREMENT,
  HoTen VARCHAR(100) NOT NULL,
  SDT VARCHAR(15),
  Email VARCHAR(100),
  DiaChi VARCHAR(200),
  DiemTichLuy INT DEFAULT 0
);

CREATE TABLE NhaCungCap (
  MaNCC INT PRIMARY KEY AUTO_INCREMENT,
  TenNCC VARCHAR(100) NOT NULL,
  SDT VARCHAR(15),
  DiaChi VARCHAR(200),
  Email VARCHAR(100)
);

CREATE TABLE LoaiHang (
  MaLoai INT PRIMARY KEY AUTO_INCREMENT,
  TenLoai VARCHAR(100) NOT NULL,
  MoTa TEXT
);

CREATE TABLE SanPham (
  MaSP INT PRIMARY KEY AUTO_INCREMENT,
  MaLoai INT NOT NULL,
  TenSP VARCHAR(100) NOT NULL,
  DonViTinh VARCHAR(50),
  GiaNhap DECIMAL(10,2) DEFAULT 0,
  GiaBan DECIMAL(10,2) DEFAULT 0,
  HanSuDung DATE,
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaLoai) REFERENCES LoaiHang(MaLoai)
);

CREATE TABLE DonDatHang (
  MaDDH INT PRIMARY KEY AUTO_INCREMENT,
  MaNCC INT NOT NULL,
  MaNV INT NOT NULL,
  NgayDat DATE,
  TrangThai VARCHAR(30),
  TongTien DECIMAL(12,2) DEFAULT 0,
  FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_DonDatHang (
  MaDDH INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(12,2) DEFAULT 0,
  ThanhTien DECIMAL(12,2) DEFAULT 0,
  PRIMARY KEY (MaDDH, MaSP),
  FOREIGN KEY (MaDDH) REFERENCES DonDatHang(MaDDH),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE PhieuNhap (
  MaPN INT PRIMARY KEY AUTO_INCREMENT,
  MaDDH INT NOT NULL,
  MaNV INT NOT NULL,
  NgayNhap DATE,
  TrangThai VARCHAR(30),
  TongTien DECIMAL(12,2) DEFAULT 0,
  FOREIGN KEY (MaDDH) REFERENCES DonDatHang(MaDDH),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_PhieuNhap (
  MaPN INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(12,2) DEFAULT 0,
  ThanhTien DECIMAL(12,2) DEFAULT 0,
  PRIMARY KEY (MaPN, MaSP),
  FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE DonHang (
  MaDH INT PRIMARY KEY AUTO_INCREMENT,
  MaKH INT,
  MaNV INT NOT NULL,
  NgayDat DATE,
  TongTien DECIMAL(12,2) DEFAULT 0,
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_DonHang (
  MaDH INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(12,2) DEFAULT 0,
  GiamGia DECIMAL(12,2) DEFAULT 0,
  ThanhTien DECIMAL(12,2) DEFAULT 0,
  PRIMARY KEY (MaDH, MaSP),
  FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE HoaDon (
  MaHD INT PRIMARY KEY AUTO_INCREMENT,
  MaDH INT NOT NULL UNIQUE,
  MaNV INT NOT NULL,
  NgayLap DATE,
  TongTien DECIMAL(12,2) DEFAULT 0,
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_HoaDon (
  MaHD INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(12,2) DEFAULT 0,
  GiamGia DECIMAL(12,2) DEFAULT 0,
  ThanhTien DECIMAL(12,2) DEFAULT 0,
  PRIMARY KEY (MaHD, MaSP),
  FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE ThanhToan (
  MaTT INT PRIMARY KEY AUTO_INCREMENT,
  MaHD INT NOT NULL,
  PhuongThuc VARCHAR(50),
  SoTien DECIMAL(12,2) DEFAULT 0,
  NgayThanhToan DATE,
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
);

CREATE TABLE PhieuXuat (
  MaPX INT PRIMARY KEY AUTO_INCREMENT,
  MaDH INT NOT NULL,
  MaNV INT NOT NULL,
  NgayXuat DATE,
  LyDoXuat VARCHAR(200),
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_PhieuXuat (
  MaPX INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(12,2) DEFAULT 0,
  ThanhTien DECIMAL(12,2) DEFAULT 0,
  PRIMARY KEY (MaPX, MaSP),
  FOREIGN KEY (MaPX) REFERENCES PhieuXuat(MaPX),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE TonKho (
  MaSP INT PRIMARY KEY,
  SoLuongTon INT DEFAULT 0,
  NgayCapNhat DATE,
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE KiemKe (
  MaKK INT PRIMARY KEY AUTO_INCREMENT,
  MaNV INT NOT NULL,
  NgayKiemKe DATE,
  GhiChu TEXT,
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_KiemKe (
  MaKK INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuongHeThong INT DEFAULT 0,
  SoLuongThucTe INT DEFAULT 0,
  ChenhLech INT DEFAULT 0,
  PRIMARY KEY (MaKK, MaSP),
  FOREIGN KEY (MaKK) REFERENCES KiemKe(MaKK),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE PhieuTraHang (
  MaPTH INT PRIMARY KEY AUTO_INCREMENT,
  MaDH INT NOT NULL,
  MaKH INT,
  MaNV INT NOT NULL,
  NgayTra DATE,
  LyDo TEXT,
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
  FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_PhieuTraHang (
  MaPTH INT NOT NULL,
  MaSP INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(12,2) DEFAULT 0,
  ThanhTien DECIMAL(12,2) DEFAULT 0,
  LyDo TEXT,
  PRIMARY KEY (MaPTH, MaSP),
  FOREIGN KEY (MaPTH) REFERENCES PhieuTraHang(MaPTH),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE KhuyenMai (
  MaKM INT PRIMARY KEY AUTO_INCREMENT,
  TenKM VARCHAR(100) NOT NULL,
  NgayBatDau DATE,
  NgayKetThuc DATE,
  PhanTramGiam DECIMAL(5,2) DEFAULT 0,
  DieuKienApDung VARCHAR(200),
  TrangThai VARCHAR(30)
);

CREATE TABLE CT_KhuyenMai (
  MaKM INT NOT NULL,
  MaSP INT NOT NULL,
  GiaTriGiam DECIMAL(12,2) DEFAULT 0,
  PRIMARY KEY (MaKM, MaSP),
  FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE CongNo (
  MaCN INT PRIMARY KEY AUTO_INCREMENT,
  MaNCC INT NOT NULL,
  MaNV INT NOT NULL,
  NgayPhatSinh DATE,
  SoTien DECIMAL(12,2) DEFAULT 0,
  SoTienDaTra DECIMAL(12,2) DEFAULT 0,
  SoTienConLai DECIMAL(12,2) DEFAULT 0,
  TrangThai VARCHAR(30),
  FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);
